services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haq-app
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
 