services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haq-app
    restart: always
    network_mode: host
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3023